### ISSUE TITLE
Minor: Make astra and astra automation legal notices consistent

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/astra#78] opened 2021-04-16 14:54 UTC
Page: [Legal notices](https://docs.netapp.com/us-en/astra/legal-notices.html)

The legal notices in the Astra docs differ slightly from the Astra Automation docs legal notices - https://docs.netapp.com/us-en/astra-automation/legal-notices.html. Things I see:

- The order of the Astra API license and Open source sections differs.
- The words in the Astra API license section headings differ slightly.
- The link in the open source section seem to be the only one where we have a link label instead of the actual URL. All other links on the page point to URLs.

**Comment by netapp-bcammett** [comment] 2021-04-19 22:24
Adam,

Thank you for providing this feedback. The two pages are now in alignment.

In regards to this comment:

> The link in the open source section seem to be the only one where we have a link label instead of the actual URL. All other links on the page point to URLs.

This is by design. For some products, the Legal notices page includes multiple Notice files, so link text is required [(here's an example).](https://docs.netapp.com/us-en/occm/reference_legal_notices.html#open-source) While the Astra page links to only one Notice file, we're using link text to be consistent with the Legal notices page for other products.

I'm going to go ahead and close this issue. Please let me know if you have any additional feedback.

Thanks again,
Ben

**Closed by netapp-bcammett** 2021-04-19 22:24 UTC
